# See https://github.com/silverstripe/silverstripe-travis-support for setup details

language: php 

php:
 - 5.3

sudo: false

env:
 - DB=MYSQL CORE_RELEASE=3.5

matrix:
  include:
    - php: 5.4
      env: DB=PGSQL CORE_RELEASE=3.2
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.4
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3.6

before_script:
 - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require "silverstripe/subsites"
 - cd ~/builds/ss

script: 
 - vendor/bin/phpunit securityreport/tests/
