mappings:
  GridFieldExportReportButton: SilverStripe\SecurityReport\Forms\GridFieldExportReportButton
  GridFieldPrintReportButton: SilverStripe\SecurityReport\Forms\GridFieldPrintReportButton
  SubsiteMemberReportExtension: SilverStripe\SecurityReport\Subsites\SubsiteMemberReportExtension
  SubsiteSecurityReport: SilverStripe\SecurityReport\Subsites\SubsiteSecurityReport
